[alias]
a = "add"
b = "build"
br = "build --release"
brr = "build --release"
r = "run"
rr = "run --release"
c = "check"
f = "fmt"
t = "nextest run"
pp = "clippy"
upd = "update"
updr = "update --dry-run"
upg = "upgrade"
trp = "tarpaulin -o Xml -v"
d = "doc"
dd = "watch -x doc"
i = "install"
o = "outdated -Rv"
au = "audit"
m = "msrv"
w = "watch"
n = "new"
lock = "generate-lockfile"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
