# import = ["~/.config/alacritty/themes/themes/github_dark.toml"]
[window]
opacity = 0.954

[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL NFP"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL NFP"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NFP"
style = "Regular"


[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
