[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL NFP"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL NFP"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NFP"
style = "Regular"
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B"
key = "Back"
mods = "Alt"
