alias copypath="pwd | pbcopy"

# python
# alias python="python3"

# local alias
alias nv= "nvim"

# cargo alias
alias cr="cargo run"
alias cb="cargo build"
# alias cc="cargo check"
alias ct="cargo test"

# -------------------------------- #
# Node Package Manager
# -------------------------------- #
# https://github.com/antfu/ni

alias nio="ni --prefer-offline"
alias s="nr start"
alias d="nr dev"
alias b="nr build"
alias bw="nr build --watch"
alias t="nr test"
alias tu="nr test -u"
alias tw="nr test --watch"
alias w="nr watch"
alias p="nr play"
alias c="nr typecheck"
alias lint="nr lint"
alias lintf="nr lint --fix"
alias release="nr release"
alias re="nr release"
